### ISSUE TITLE
Inconsistent decimal places

### ISSUE THREAD

**Issue by Davoleo** [zambodev/amazon_price_tracker#1]
Currently the output of the app is like this:
![image](https://github.com/zambodev/amazon_price_tracker/assets/24458276/54f23eb0-968a-43d7-8fd3-87715ff21735)

I think it would look better and make more sense, since it's a price, to use a fixed notation of 2 decimal places instead of how they're displayed at the moment

**Comment by zambodev** [comment]
Made constant 2 decimals and moved the sign for a better aesthetics.
![image](https://github.com/zambodev/amazon_price_tracker/assets/46820947/2cb4ddc7-6ff6-4f78-9d60-9af25a302f86)
