### ISSUE TITLE
Terminal Embedded Links 

### ISSUE THREAD

**Issue by Davoleo** [zambodev/amazon_price_tracker#3]
idk if there's a standard format to create embedded links in terminal interfaces [like this one](https://example.com) but even adding the raw link to the display would be cool enough, for example as a new item under Latest or just under the title
![image](https://github.com/zambodev/amazon_price_tracker/assets/24458276/b2767836-32b6-4c87-a45a-d8974e85cc17)
One important thing if we decide to go for the raw link I think we should try to strip it from random query args since amazon links are known to be very long and would be cluttering the clean look of the current interface

**Comment by zambodev** [comment]
Feature added in this commit 9ce95dbf8518027db42ef224b6ba871bb88c4a1f
